name: Changeset Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  changeset-check:
    name: Check for Changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changeset
        run: |
          if [ -z "$(ls .changeset/*.md 2>/dev/null | grep -v README)" ]; then
            echo "::warning::No changeset found. Please run 'yarn changeset' to document your changes."
          else
            echo "✅ Changeset found!"
          fi
