name: Frontend Build Check

on:
  pull_request:

jobs:
  filter: # 只在 frontend 或相關根目錄檔案變動時觸發
    name: Detect changed files
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.paths.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - name: Filter for frontend changes
        id: paths
        uses: dorny/paths-filter@v2
        with:
          filters: |
            frontend:
              - 'packages/frontend/**'
              - 'yarn.lock'
              - 'package.json'
              - '.yarnrc.yml'

  build-frontend:
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.frontend == 'true'

    steps:
      # Has to be run before actions/setup-node.
      # See: https://github.com/actions/setup-node/issues/480
      - name: Enable corepack for yarn
        run: corepack enable

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable # 使用 --immutable 或 --frozen-lockfile 確保 lock 檔一致

      - name: Build frontend package
        run: yarn workspace @twreporter/congress-dashboard-frontend build
        working-directory: ./ # 在根目錄執行 workspace 指令

  skip-frontend:
    name: No frontend changes → Skip
    needs: filter
    if: needs.filter.outputs.frontend != 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "🛑 No frontend‐related changes, skipping build."
