name: Frontend Build Check

on:
  pull_request:
    paths: # 只在 frontend 或相關根目錄檔案變動時觸發
      - 'packages/frontend/**'
      - 'yarn.lock'
      - 'package.json'
      - '.yarnrc.yml'

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      # Has to be run before actions/setup-node.
      # See: https://github.com/actions/setup-node/issues/480
      - name: Enable corepack for yarn
        run: corepack enable

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable # 使用 --immutable 或 --frozen-lockfile 確保 lock 檔一致

      - name: Build frontend package
        run: yarn workspace @twreporter/congress-dashboard-frontend build
        working-directory: ./ # 在根目錄執行 workspace 指令
